### ISSUE TITLE
ImportError: No module named eszcp.cmd.proxy

### ISSUE THREAD

**Issue by mate201** [apolloliu/zcp#1]
Hello apolloliu. I get this error then I try to run eszcp-polling. What it may be ?

Traceback (most recent call last):
  File "/usr/local/bin/eszcp-polling", line 4, in <module>
    __import__('pkg_resources').run_script('UNKNOWN==1.0.1', 'eszcp-polling')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/UNKNOWN-1.0.1-py2.7.egg/EGG-INFO/scripts/eszcp-polling", line 13, in <module>
    from eszcp.cmd.proxy import main
ImportError: No module named eszcp.cmd.proxy

**Comment by apolloliu** [comment]
Hi aizikil,
I'm so glad that you could use the software and give me some feedbacks.
Sorry, it should be zcp.cmd.proxy. eszcp is the original root directory.
I will fix it soon about this.
cheers,
Hanxi Liu

**Comment by mate201** [comment]
No problem.

When I'm running "pyhton setup.py install" on the latest code I receive this error -

`error: file '/home/ubuntu/zabbix-scripts/zcp/bin/zcp-polling' does not exist `

Inside the bin folder there is eszcp-polling file, so I've renamed it to zcp-polling and installed without any error.

But then I run eszcp-polling I receive this error -
```
Traceback (most recent call last):
  File "/usr/local/bin/eszcp-polling", line 4, in <module>
    __import__('pkg_resources').run_script('UNKNOWN==1.0.1', 'eszcp-polling')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1496, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'eszcp-polling'
```
It seems for me that it's some naming problem. Hope that helps.

**Comment by apolloliu** [comment]
I have updated the README.rst and rename eszcp-polling. And you could install it again and try zcp-polling.

**Comment by mate201** [comment]
Thank you !

I've got new one  - 

```
Traceback (most recent call last):
  File "/usr/local/bin/zcp-polling", line 4, in <module>
    __import__('pkg_resources').run_script('UNKNOWN==1.0.1', 'zcp-polling')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/UNKNOWN-1.0.1-py2.7.egg/EGG-INFO/scripts/zcp-polling", line 13, in <module>
    from zcp.cmd.proxy import main
  File "/usr/local/lib/python2.7/dist-packages/UNKNOWN-1.0.1-py2.7.egg/zcp/cmd/proxy.py", line 41, in <module>
    log.init_log()
  File "/usr/local/lib/python2.7/dist-packages/UNKNOWN-1.0.1-py2.7.egg/zcp/common/log.py", line 34, in init_log
    raise LogConfigurationNotFound(msg)
zcp.exceptions.LogConfigurationNotFound: Please configure correctly and be sure file log path exists!

```
Here goes part of my proxy.conf under /etc/zcp/ - 

```
[log]
#log configuration file
log_dir = /var/log/
log_file = zcp.log

```

**Comment by apolloliu** [comment]
You should update proxy.conf with the latest configurations. Then copy etc/logging_config.conf under /etc/zcp/. With logging_config.conf, you can choose the log file path in it and the default is /var/log/zcp/zcp.log.
Thanks for your feedbacks.

**Comment by mate201** [comment]
Thank you ! Didn't notice that !

I've got new mistake -

```
2017-05-04 12:33:03,475 26708 /usr/local/lib/python2.7/dist-packages/UNKNOWN-1.0.1-py2.7.egg/zcp/cmd/proxy.py [line:117] INFO - -------------- Starting Zabbix Ceilometer Proxy --------------
Traceback (most recent call last):
  File "/usr/local/bin/zcp-polling", line 4, in <module>
    __import__('pkg_resources').run_script('UNKNOWN==1.0.1', 'zcp-polling')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/UNKNOWN-1.0.1-py2.7.egg/EGG-INFO/scripts/zcp-polling", line 16, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/UNKNOWN-1.0.1-py2.7.egg/zcp/cmd/proxy.py", line 118, in main
    init_zcp(processes)
  File "/usr/local/lib/python2.7/dist-packages/UNKNOWN-1.0.1-py2.7.egg/zcp/cmd/proxy.py", line 53, in init_zcp
    ks_client = Client(conf_file)
  File "/usr/local/lib/python2.7/dist-packages/UNKNOWN-1.0.1-py2.7.egg/zcp/keystone_client.py", line 78, in __init__
    self.domain_keystone = ks_client_v3.Client(**v3_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v3/client.py", line 238, in __init__
    self.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 581, in authenticate
    resp = self.get_raw_token_from_identity_service(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v3/client.py", line 314, in get_raw_token_from_identity_service
    return plugin.get_auth_ref(self.session)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/auth/identity/v3/base.py", line 191, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/session.py", line 545, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/session.py", line 445, in request
    raise exceptions.from_response(resp, method, url)
keystoneauth1.exceptions.http.Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-7da14d0c-7b2b-42f3-90b7-d8a0ace89c34)
```
I'm using Mitaka release as a testing environment, could that be a problem ?


proxy.conf -
```

[log]
#log configuration file
log_dir = /etc/zcp/
log_file = logging_config.conf

[zabbix_configs]
zabbix_admin_user = Admin
zabbix_admin_pass = *
zabbix_host = localhost
zabbix_port = 10051

[os_rabbitmq]
rabbit_hosts = 10.10.10.248
rabbit_user = nova
rabbit_pass = *
rabbit_port = 5672
rabbit_virtual_host = /
max_retries= -1
retry_interval=5

[ceilometer_configs]
ceilometer_api_host = 10.10.10.33
ceilometer_api_port = 8777


[keystone_authtoken]
region_name = RegionOne
username = admin
password = *
project_name = admin
domain_name = Default
user_domain_name = Default
project_domain_name = Default
#Defaut
auth_url = http://10.10.10.39:35357/v3
keystone_port = 35357
keystone_host = 10.10.10.39

[nova_configs]
nova_host = 10.10.10.252
nova_port = 8774

[mongodb]
max_retries=3
retry_interval=2
#connection = mongodb://ceilometer:MQj7MDEU@10.10.10.70/ceilometer
connection = mongodb://10.10.10.70:27017/ceilometer
mapping_file = /etc/ceilometer/mapping.json

[zcp_configs]
# Interval in seconds
polling_interval = 300
# template name to be created in Zabbix
template_name = Template ZCP
# how to retrive ceilometer metrics, and then polling them into zabbix
# support values: ceilometer,mongodb, default is mongodb
polling_handler= mongodb



```

One more thing. How do I should correctly configure this line ?

`connection = mongodb://10.10.10.70:27017/ceilometer`

**Comment by apolloliu** [comment]
Which versions of keystoneclient, novaclient and ceilometerclient are you use?
Version  info in my environment follows:

    python-keystoneclient-1.7.2-3.4.4.1.el7.centos.es.noarch
    python-novaclient-2.30.1-3.4.4.1.el7.centos.es.noarch
    python-ceilometerclient-1.5.1-3.4.4.1.el7.centos.es.noarch

Btw, I suggest you choose to “polling_handler = ceilometer” because the mongo driver for our company.
There'll be a session in Boston Summit about ZCP named "Integrating Ceilometer with the
existing monitoring solution using
Zabbix". If you're interested in it, I'd communicate with you about this.  I'm so appreciate it If you'd like to contribute to zcp.

**Comment by mate201** [comment]
It's OpenStack Miataka installed by juju.

Keystone server
```
Name: python-keystoneclient
Version: 2.3.1
```

Ceilometer server
```
Name: python-novaclient
Version: 3.3.1

Name: python-ceilometerclient
Version: 2.4.0
```
I'm sorry but I think that I don't know python good enough to code a such project. It's possible that I would cause a trouble not a help ))) Anyway I can help you with testing. 

By the way, have you seen this prototype [https://github.com/egiorgio/ProZaC](https://github.com/egiorgio/ProZaC)  ?

**Comment by apolloliu** [comment]
Actually we developed this for Liberty OpenStack. My collaborative developer and I are looking forward to seeing if the project is worthy doing long-term development to make it compatible  and available for mitaka or later version. Also, I think it's good chance to practice using python If you'd like to contribute.

yeah, I have seen that: https://github.com/OneSourceConsult/ZabbixCeilometer-Proxy
It's the original inspiration of our zcp.

**Comment by mate201** [comment]
Sorry, but my executives didn't give me a green light (
Maybe later we will return to this problem. Anyway thank you for your time !

**Comment by nagaravishankar** [comment]
Hello apolloliu
Can you please share any procedure to create mapping.json fle ? or if you have some sample mapping.json, please share.

**Comment by apolloliu** [comment]
@nagaravishankar Hope this help! http://pastebin.ubuntu.com/26055660/

**Comment by 8wlgns** [comment]
Hi! @apolloliu @nagaravishankar !! I have same problem too.

I also get some same keystone sessions issue too.
my openstack version is ockata.. so maybe related with version problem??


[root@rsosc workspace(keystone_admin)]# ./zcp/bin/zcp-polling 
2017-12-12 16:30:54,565 24376 /usr/lib/python2.7/site-packages/zcp/cmd/proxy.py [line:117] INFO - -------------- Starting Zabbix Ceilometer Proxy --------------
/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py:136: UserWarning: Using keystoneclient sessions has been deprecated. Please update your software to use keystoneauth1.
  warnings.warn('Using keystoneclient sessions has been deprecated. '
Traceback (most recent call last):
  File "./zcp/bin/zcp-polling", line 16, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/zcp/cmd/proxy.py", line 118, in main
    init_zcp(processes)
  File "/usr/lib/python2.7/site-packages/zcp/cmd/proxy.py", line 82, in init_zcp
    zabbix_hdl.first_run()
  File "/usr/lib/python2.7/site-packages/zcp/zabbix_handler.py", line 149, in first_run
    self.check_instances()
  File "/usr/lib/python2.7/site-packages/zcp/zabbix_handler.py", line 47, in with_logging
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zcp/zabbix_handler.py", line 287, in check_instances
    servers = [i.to_dict() for i in self.nv_client.instance_get_all()]
  File "/usr/lib/python2.7/site-packages/zcp/nova_client.py", line 33, in with_logging
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zcp/nova_client.py", line 85, in instance_get_all
    search_opts=search_opts)
  File "/usr/lib/python2.7/site-packages/novaclient/v2/servers.py", line 861, in list
    "servers")
  File "/usr/lib/python2.7/site-packages/novaclient/base.py", line 254, in _list
    resp, body = self.api.client.get(url)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 217, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/lib/python2.7/site-packages/novaclient/client.py", line 74, in request
    **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 374, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/adapter.py", line 142, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/lib/python2.7/site-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 491, in request
    auth_headers = self.get_auth_headers(auth)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 818, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/plugin.py", line 90, in get_headers
    token = self.get_token(session)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 90, in get_token
    return self.get_access(session).auth_token
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/base.py", line 136, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/generic/base.py", line 198, in get_auth_ref
    return self._plugin.get_auth_ref(session, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/identity/v2.py", line 65, in get_auth_ref
    authenticated=False, log=False)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 766, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python2.7/site-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/keystoneauth1/session.py", line 655, in request
    raise exceptions.from_response(resp, method, url)
keystoneauth1.exceptions.http.Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-61c82253-d06a-4074-abe2-ab1af697833b)
