### ISSUE TITLE
keystoneauth1.exceptions

### ISSUE THREAD

**Issue by nephilimboy** [apolloliu/zcp#3]
hi ,,,
thanks for this repo looking for something like proxy for zabbix for a while,,,
I have an issue when running  zcp-polling , it says : 
```
 2017-05-24 14:43:54,906 26781 /usr/local/lib/python2.7/dist-packages/zcp/cmd/proxy.py [line:117] INFO - -------------- Starting Zabbix Ceilometer Proxy --------------
Traceback (most recent call last):
  File "./zcp-polling", line 16, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/zcp/cmd/proxy.py", line 118, in main
    init_zcp(processes)
  File "/usr/local/lib/python2.7/dist-packages/zcp/cmd/proxy.py", line 53, in init_zcp
    ks_client = Client(conf_file)
  File "/usr/local/lib/python2.7/dist-packages/zcp/keystone_client.py", line 78, in __init__
    self.domain_keystone = ks_client_v3.Client(**v3_kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v3/client.py", line 231, in __init__
    self.authenticate()
  File "/usr/lib/python2.7/dist-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 578, in authenticate
    resp = self.get_raw_token_from_identity_service(**kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v3/client.py", line 307, in get_raw_token_from_identity_service
    return plugin.get_auth_ref(self.session)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/auth/identity/v3/base.py", line 191, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/session.py", line 519, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python2.7/dist-packages/positional/__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/session.py", line 419, in request
    raise exceptions.from_response(resp, method, url)
keystoneauth1.exceptions.http.Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-8e8f7ec1-fc12-4123-8010-e1b3c7530e76)
```
i'm sure that my keystone is running and my configuration is all correct, so why i'm getting this error,,, do you have any idea abt this?  is there any version mismatching problem exists when using  Newton openstack and zcp together?
thanks in advance

**Comment by apolloliu** [comment]
Hi nephilimboy ,

Thank you for using zcp and give some feedback. The project is written for Liberty OpenStack. So it may have some mismatching problems with Newton version. I 'd like to implement it for match Newton Openstack or later version. I also very appreciate it if you can do some contributing for this project.

**Comment by nagaravishankar** [comment]
The above issue is still persists, but it can be fixed by adding the admin role to the domain as 
openstack role add --domain Default --user admin  admin
