### ISSUE TITLE
Newton support

### ISSUE THREAD

**Issue by pradhanparas** [apolloliu/zcp#4]
Does this support Newton?

I am getting keystoneauth1.exceptions.http.Unauthorized when running zcp-polling . May be related to package versions?

Thanks
Paras.

**Comment by pradhanparas** [comment]
This is the error that I am seeing.

[root@zabbix bin]# ./zcp-polling
2018-03-20 21:09:18,990 7472 /usr/lib/python2.7/site-packages/zcp/cmd/proxy.py [line:117] INFO - -------------- Starting Zabbix Ceilometer Proxy --------------
Traceback (most recent call last):
  File "./zcp-polling", line 16, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/zcp/cmd/proxy.py", line 118, in main
    init_zcp(processes)
  File "/usr/lib/python2.7/site-packages/zcp/cmd/proxy.py", line 82, in init_zcp
    zabbix_hdl.first_run()
  File "/usr/lib/python2.7/site-packages/zcp/zabbix_handler.py", line 144, in first_run
    self.proxies = self.check_proxies()
  File "/usr/lib/python2.7/site-packages/zcp/zabbix_handler.py", line 193, in check_proxies
    domains = [domain for domain in self.ks_client.get_domains()]
  File "/usr/lib/python2.7/site-packages/zcp/keystone_client.py", line 45, in with_logging
    raise e
keystoneauth1.exceptions.catalog.EndpointNotFound: Endpoint for identity service
